// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"cases/layout/args"
	"github.com/mgutz/razor"
	. "kp/models"
	"tpl/helper"
)

// Argsbug is generated
func Argsbug(totalMessage int, u *User) *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()

	messages := []string{}
	__buffer.WriteString("\n\n<p>")
	__buffer.WriteSafe(gorazor.Itoa(args(messages...)))
	__buffer.WriteString("</p>")

	return __buffer
}
