// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor"
)

// Bug is generated
func Bug() *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()
	__buffer.WriteString("<html>\n  <head>\n    <title>Title</title>\n  </head>\n\n  <body>\n  Body\n  </body>\n</html>")

	return __buffer
}
