// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor"
)

// Bug8 is generated
func Bug8() *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()
	var l *Locale
	__buffer.WriteString("\n<span>")
	__buffer.WriteSafe(l.T("for"))
	__buffer.WriteString("</span>")

	return __buffer
}
