// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor"
)

// Codeblock is generated
func Codeblock() *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()

	return __buffer
}
