// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"cases/layout/base"
	"github.com/mgutz/razor"
)

// Forward is generated
func Forward() *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()
	var content string
	var err string

	//hello word
	/* hello this */

	return __buffer
}
