// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"cases/layout/base"
	"github.com/mgutz/razor"
	"kp/models"
)

// Index is generated
func Index() *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()
	var users []*models.User
	var total int
	var limit int
	var offset int
	__buffer.WriteString("\n\n<h2 class=\"sub-header\">用户总数：")
	__buffer.WriteSafe(gorazor.Itoa(total))
	__buffer.WriteString("</h2>\n<div class=\"table-responsive\">\n	<table class=\"table table-striped\">\n		<thead>\n			<tr>\n				<th>名字</th>\n				<th>电邮</th>\n				<th>编辑</th>\n			</tr>\n		</thead>\n		<tbody>\n			")
	for _, u := range users {

		__buffer.WriteString("<tr>\n				<td>")
		__buffer.WriteSafe(u.Name)
		__buffer.WriteString("</td>\n				<td>")
		__buffer.WriteSafe(u.Email)
		__buffer.WriteString("</td>\n				<td><a href=\"/admin/user/edit?id=")
		__buffer.WriteSafe(u.ID.Hex())
		__buffer.WriteString("\">编辑</a></td>\n			</tr>")

	}
	__buffer.WriteString("\n		</tbody>\n	</table>\n</div>")

	__js := func() *razor.SafeBuffer {
		__buffer := razor.NewSafeBuffer()
		return __buffer
	}

	__title := func() *razor.SafeBuffer {
		__buffer := razor.NewSafeBuffer()

		__buffer.WriteString("用户管理")

		return __buffer
	}

	return __buffer
}
