// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor"
)

// Keyword is generated
func Keyword() *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()
	__buffer.WriteString("BLK(<span>rememberingsteve@apple.com ")
	__buffer.WriteSafe(username)
	__buffer.WriteString("</span>)BLK")

	return __buffer
}
