// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor"
)

// Layout is generated
func Layout() *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()
	var body string
	var title string
	var side string
	__buffer.WriteString("\n<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\" />")
	__buffer.WriteSafe(title)
	__buffer.WriteString("\n</head>\n<body>\n<div>")
	__buffer.WriteSafe(body)
	__buffer.WriteString("</div>\n<div>")
	__buffer.WriteSafe(side)
	__buffer.WriteString("</div>\n</body>\n</html>")

	return __buffer
}
