// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor"
	. "kp/models"
)

// Msg is generated
func Msg() *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()
	var u *User

	getName := func(u *User) string {
		return "(" + u.Name + ")"
	}

	var username string
	if u.Email != "" {
		username = getName(u) + "(" + u.Email + ")"
	}
	__buffer.WriteString("\n<div class=\"welcome\">\n<h4>Hello ")
	__buffer.WriteSafe(username)
	__buffer.WriteString("</h4>\n\n<div>")
	__buffer.WriteSafe((u.Intro))
	__buffer.WriteString("</div>\n</div>")

	return __buffer
}
