// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor"
)

// Nosection is generated
func Nosection() *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()
	__buffer.WriteString("\n\n<h1>Hello</h1>")

	__buffer = NosectionLayout(__buffer, nil)
	return __buffer
}
