// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor"
)

// NosectionLayout is generated
func NosectionLayout(__body *razor.SafeBuffer, __sections *razor.Sections) *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()

	RenderBody := func() *razor.SafeBuffer {
		return __body
	}
	__buffer.WriteSafe(RenderBody())

	return __buffer
}
