// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor"
)

// NosectionLayout is generated
func NosectionLayout(body *razor.SafeBuffer, psections *razor.Sections) *razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()

	RenderBody := func() *razor.SafeBuffer {
		return body
	}
	_buffer.WriteSafe(RenderBody())

	return _buffer
}
