// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor"
)

// Nosection is generated
func Nosection() *razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	_buffer.WriteString("\n\n<h1>Hello</h1>")

	_buffer = NosectionLayout(_buffer, nil)
	return _buffer
}
