// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor"
)

// Quote is generated
func Quote() *razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	_buffer.WriteString("<html>'text'</html>")

	return _buffer
}
