// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"dm"
	"github.com/mgutz/razor"
	"zfw/models"
	. "zfw/tplhelper"
)

// Scope is generated
func Scope() *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()
	var obj *models.Widget
	{
		data, dmType := dm.GetData(obj.PlaceHolder)

		if dmType == "simple" {
			obj.StringList = data.([]string)

			__buffer.WriteString("<div>")
			__buffer.WriteSafe((SelectPk(obj)))
			__buffer.WriteString("</div>")

		} else {
			node := data.(*dm.DMTree)

			__buffer.WriteString("<div class=\"form-group ")
			__buffer.WriteSafe(GetErrorClass(obj))
			__buffer.WriteString("\">\n  <label for=\"")
			__buffer.WriteSafe(obj.Name)
			__buffer.WriteString("\" class=\"col-sm-2 control-label\">")
			__buffer.WriteSafe(obj.Label)
			__buffer.WriteString("</label>\n  <div class=\"col-sm-10\">\n    <select class=\"form-control\" name=\"")
			__buffer.WriteSafe(obj.Name)
			__buffer.WriteString("\" ")
			__buffer.WriteSafe(BoolStr(obj.Disabled, "disabled"))
			__buffer.WriteString(">\n      ")
			for _, option := range node.Keys {
				if values, ok := node.Values[option]; ok {

					__buffer.WriteString("<optgroup label=\"")
					__buffer.WriteSafe(option)
					__buffer.WriteString("\">\n        ")
					for _, value := range values {
						if value == obj.Value {

							__buffer.WriteString("<option selected>")
							__buffer.WriteSafe(value)
							__buffer.WriteString("</option>")

						} else {

							__buffer.WriteString("<option>")
							__buffer.WriteSafe(value)
							__buffer.WriteString("</option>")

						}
					}
					__buffer.WriteString("\n      </optgroup>")

				} else {
					if option == obj.Value {

						__buffer.WriteString("<option selected>")
						__buffer.WriteSafe(option)
						__buffer.WriteString("</option>")

					} else {

						__buffer.WriteString("<option>")
						__buffer.WriteSafe(option)
						__buffer.WriteString("</option>")

					}
				}
			}
			__buffer.WriteString("\n    </select>\n    ")
			if obj.ErrorMsg != "" {

				__buffer.WriteString("<span class=\"label label-danger\">")
				__buffer.WriteSafe(obj.ErrorMsg)
				__buffer.WriteString("</span>")

			}
			__buffer.WriteString("\n  </div>\n</div>")
		}
	}

	return __buffer
}
