// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor"
	"kp/models"
	"tpl/admin/layout/base"
)

// Sectionbug is generated
func Sectionbug() *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()

	__js := func() *razor.SafeBuffer {
		__buffer := razor.NewSafeBuffer()
		for _, jsFile := range ctx.GetJS() {

			__buffer.WriteString("<script src=\"")
			__buffer.WriteSafe(jsFile)
			__buffer.WriteString("\"></script>")

		}
		return __buffer
	}

	return __buffer
}
