// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor"
)

// SectionLayout is generated
func SectionLayout(__body *razor.SafeBuffer, __sections *razor.Sections) *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()

	RenderBody := func() *razor.SafeBuffer {
		return __body
	}

	RenderSection := func(section string, required ...bool) *razor.SafeBuffer {
		sections := *__sections
		text := sections[section]
		isRequired := len(required) == 1 && required[0]
		if text == nil && isRequired {
			return razor.NewSafeBufferString("<div style='color:white; background-color: red'>SECTION " + section + " is required!<div>")
		}
		return text
	}
	__buffer.WriteSafe(RenderBody())
	__buffer.WriteString("\n\n<div class=\"side\">\n    ")
	__buffer.WriteSafe(RenderSection("side"))
	__buffer.WriteString("\n</div>")

	return __buffer
}
