// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor"
)

// SectionLayout is generated
func SectionLayout(body *razor.SafeBuffer, psections *razor.Sections) *razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()

	RenderBody := func() *razor.SafeBuffer {
		return body
	}

	RenderSection := func(section string, required ...bool) *razor.SafeBuffer {
		sections := *psections
		text := sections[section]
		isRequired := len(required) == 1 && required[0]
		if text == nil && isRequired {
			return razor.NewSafeBufferString("<div style='color:white; background-color: red'>SECTION " + section + " is required!<div>")
		}
		return text
	}
	_buffer.WriteSafe(RenderBody())
	_buffer.WriteString("\n\n<div class=\"side\">\n    ")
	_buffer.WriteSafe(RenderSection("side"))
	_buffer.WriteString("\n</div>")

	return _buffer
}
