// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor"
)

// Var is generated
func Var() *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()
	var totalMessage int

	return __buffer
}
