// DO NOT EDIT! Auto-generated by github.com/mgutz/gorazor
package layout

import (
	"github.com/mgutz/razor/razor"
	"strconv"
	"zfw/models"
)

func Args(...*models.Widget) razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()

	size := strconv.Itoa(12 / len(objs))

	return _buffer
}
