// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package layout

import (
	"github.com/mgutz/razor"
	"strconv"
	"zfw/models"
)

// Args is generated
func Args(...*models.Widget) *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()

	size := strconv.Itoa(12 / len(objs))

	return __buffer
}
