// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"cases/layout/args"
	"github.com/mgutz/razor/razor"
	. "kp/models"
	"tpl/helper"
)

// Argsbug is generated
func Argsbug(totalMessage int, u *User) *razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	locals := razor.Locals
	if locals != nil {
		// avoids not declared error if locals is not used
	}

	messages := []string{}
	_buffer.WriteString("\n\n<p>")
	_buffer.WriteSafe(gorazor.Itoa(args(messages...)))
	_buffer.WriteString("</p>")

	return _buffer
}
