// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor/razor"
)

// Blk is generated
func Blk() *razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()

	return _buffer
}
