// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor/razor"
)

//Bug is generated
func Bug() razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	_buffer.WriteString("<html>\n  <head>\n    <title>Title</title>\n  </head>\n\n  <body>\n  Body\n  </body>\n</html>")

	return _buffer
}
