// DO NOT EDIT! Auto-generated by github.com/mgutz/gorazor
package cases

import (
	"github.com/mgutz/razor/razor"
)

func Codeblock() razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()

	return _buffer
}
