// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor/razor"
)

// Double_quote is generated
func Double_quote() razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	_buffer.WriteString("<meta charset=\"utf-8\" />")

	return _buffer
}
