// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor/razor"
)

// Email is generated
func Email() *razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	_buffer.WriteString("<span>rememberingsteve@apple.com ")
	_buffer.WriteSafe(username)
	_buffer.WriteString("</span>")

	return _buffer
}
