// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"cases/layout/base"
	"github.com/mgutz/razor/razor"
	. "kp/models"
	"tpl/helper"
)

// End is generated
func End() *razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	locals := razor.Locals
	if locals != nil {
		// avoids not declared error if locals is not used
	}
	var totalMessage int
	var u *User
	_buffer.WriteSafe(helper.Header())
	_buffer.WriteSafe(helper.Msg(u))
	for i := 0; i < 2; i++ {
		if totalMessage > 0 {
			if totalMessage == 1 {

				_buffer.WriteString("<p>")
				_buffer.WriteSafe(u.Name)
				_buffer.WriteString(" has 1 message</p>")

			} else {

				_buffer.WriteString("<p>")
				_buffer.WriteSafe(u.Name)
				_buffer.WriteString(" has ")
				_buffer.WriteSafe(gorazor.Itoa(totalMessage))
				_buffer.WriteString(" messages</p>")

			}
		} else {

			_buffer.WriteString("<p>")
			_buffer.WriteSafe(u.Name)
			_buffer.WriteString(" has no messages</p>")

		}
	}
	{
		for i := 0; i < 2; i++ {
			if totalMessage > 0 {
				if totalMessage == 1 {

					_buffer.WriteString("<p>")
					_buffer.WriteSafe(u.Name)
					_buffer.WriteString(" has 1 message</p>")

				} else {

					_buffer.WriteString("<p>")
					_buffer.WriteSafe(u.Name)
					_buffer.WriteString(" has ")
					_buffer.WriteSafe(gorazor.Itoa(totalMessage))
					_buffer.WriteString(" messages</p>")

				}
			} else {

				_buffer.WriteString("<p>")
				_buffer.WriteSafe(u.Name)
				_buffer.WriteString(" has no messages</p>")

			}
		}
	}
	{
		switch totalMessage {
		case 1:

			_buffer.WriteString("<p>")
			_buffer.WriteSafe(u.Name)
			_buffer.WriteString(" has 1  message</p>")

		case 2:

			_buffer.WriteString("<p>")
			_buffer.WriteSafe(u.Name)
			_buffer.WriteString(" has 2 messages</p>")

		default:

			_buffer.WriteString("<p>")
			_buffer.WriteSafe(u.Name)
			_buffer.WriteString(" has no messages</p>")

		}
	}
	_buffer.WriteSafe(helper.Footer())

	title := func() *razor.SafeBuffer {
		_buffer := razor.NewSafeBuffer()

		_buffer.WriteString("<title>")
		_buffer.WriteSafe(u.Name)
		_buffer.WriteString("'s homepage</title>")

		return _buffer
	}

	side := func() *razor.SafeBuffer {
		_buffer := razor.NewSafeBuffer()

		return _buffer
	}

	_sections := make(razor.Sections)
	_sections["title"] = title()
	_sections["side"] = side()

	return _buffer
}
