// DO NOT EDIT! Auto-generated by github.com/mgutz/gorazor
package cases

import (
	"github.com/mgutz/razor/razor"
)

func Footer() razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	_buffer.WriteString("<div>copyright 2014</div>")

	return _buffer
}
