// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"cases/layout/base"
	"github.com/mgutz/razor/razor"
)

// Forward is generated
func Forward() *razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	locals := razor.Locals
	if locals != nil {
		// avoids not declared error if locals is not used
	}
	var content string
	var err string

	//hello word
	/* hello this */

	return _buffer
}
