// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"cases/layout"
	"github.com/mgutz/razor/razor"
)

//Forward is generated
func Forward() razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	var content string
	var err string

	//hello word
	/* hello this */

	return _buffer
}
