// DO NOT EDIT! Auto-generated by github.com/mgutz/gorazor
package cases

import (
	"github.com/mgutz/razor/razor"
)

func Header() razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	_buffer.WriteString("<div>Page Header</div>")

	return _buffer
}
