// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"cases/layout"
	"github.com/mgutz/razor/razor"
	"kp/models"
)

//Index is generated
func Index() razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	var users []*models.User
	var total int
	var limit int
	var offset int
	_buffer.WriteString("\n\n<h2 class=\"sub-header\">用户总数：")
	_buffer.WriteSafe(gorazor.Itoa(total))
	_buffer.WriteString("</h2>\n<div class=\"table-responsive\">\n	<table class=\"table table-striped\">\n		<thead>\n			<tr>\n				<th>名字</th>\n				<th>电邮</th>\n				<th>编辑</th>\n			</tr>\n		</thead>\n		<tbody>\n			")
	for _, u := range users {

		_buffer.WriteString("<tr>\n				<td>")
		_buffer.WriteSafe(u.Name)
		_buffer.WriteString("</td>\n				<td>")
		_buffer.WriteSafe(u.Email)
		_buffer.WriteString("</td>\n				<td><a href=\"/admin/user/edit?id=")
		_buffer.WriteSafe(u.ID.Hex())
		_buffer.WriteString("\">编辑</a></td>\n			</tr>")

	}
	_buffer.WriteString("\n		</tbody>\n	</table>\n</div>")

	js := func() razor.SafeBuffer {
		_buffer := razor.NewSafeBuffer()
		return _buffer
	}

	title := func() razor.SafeBuffer {
		_buffer := razor.NewSafeBuffer()

		_buffer.WriteString("用户管理")

		return _buffer
	}

	return _buffer
}
