// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor/razor"
	"github.com/sunfmin/gorazortests/models"
)

// Inline_var is generated
func Inline_var() razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	_buffer.WriteString("\n\n<body>")
	_buffer.WriteSafe(Hello("Felix Sun", "h1", 30, &models.Author{"Van", 20}, 10))
	_buffer.WriteString("\n</body>")

	return _buffer
}
