// DO NOT EDIT! Auto-generated by github.com/mgutz/gorazor
package cases

import (
	"dm"
	"github.com/mgutz/razor/razor"
	"zfw/models"
	. "zfw/tplhelper"
)

func Scopebug() razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	var obj *models.Widget
	{
		if 1 == 2 {
		} else {
			values := []int{}
			for _, v := range values {
				if v, ok := v.(type); ok {

					_buffer.WriteString("<a>\n					")
					for _, v := range values {
					}
					_buffer.WriteString("\n				</a>")

				} else {

				}
			}
		}
	}

	return _buffer
}
