// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor/razor"
	"kp/models"
	"tpl/admin/layout"
)

//Sectionbug is generated
func Sectionbug() razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()

	js := func() razor.SafeBuffer {
		_buffer := razor.NewSafeBuffer()
		for _, jsFile := range ctx.GetJS() {

			_buffer.WriteString("<script src=\"")
			_buffer.WriteSafe(jsFile)
			_buffer.WriteString("\"></script>")

		}
		return _buffer
	}

	return _buffer
}
