// DO NOT EDIT! Auto-generated by github.com/mgutz/gorazor
package cases

import (
	"github.com/mgutz/razor/razor"
)

func Var() razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	var totalMessage int

	return _buffer
}
