// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"github.com/mgutz/razor/razor"
)

//Var is generated
func Var() razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	var totalMessage int

	return _buffer
}
