// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package admin

import (
	"github.com/mgutz/razor"
	"github.com/mgutz/razor/example/models"
	"github.com/mgutz/razor/example/views"
	"github.com/mgutz/razor/html"
)

// Index is generated
func Index(user *models.User) *razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	locals := razor.Locals
	if locals != nil {
		// avoids not declared error if locals is not used
	}
	data := razor.ViewData{
		"title": "Razor + Go = love",
	}
	_buffer.WriteString("\n\n<!-- use of a section for body is more consistent and simplifies code -->")

	body := func() *razor.SafeBuffer {
		_buffer := razor.NewSafeBuffer()

		_buffer.WriteString("<!-- if this was in body, views would have to be escaped as ")
		_buffer.WriteSafe(views)
		_buffer.WriteString(" -->\n  views.Heading2(\"Razor rocks\")\n\n  <p>Escaped: ")
		_buffer.WriteSafe(UnsafeHello(user.Name))
		_buffer.WriteString("</p>")

		_buffer.WriteString("<p>Unescaped: ")
		_buffer.WriteSafe(SafeHello(user.Name))
		_buffer.WriteString("</p>")

		_buffer.WriteString("<!-- avoid using Raw, create a function that returns SafeBuffer instead -->\n  html.Raw(\"<h2>Heading 2</h2>")
		return _buffer
	}

	js := func() *razor.SafeBuffer {
		_buffer := razor.NewSafeBuffer()

		_buffer.WriteString("<script>\n    alert('Hello, ")
		_buffer.WriteSafe(user.Name)
		_buffer.WriteString("');\n  </script>")

		return _buffer
	}

	_sections := make(razor.Sections)
	_sections["body"] = body()
	_sections["js"] = js()
	_buffer = Layout(_sections, data)
	return _buffer
}
