// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package admin

import (
	"github.com/mgutz/razor"
	"github.com/mgutz/razor/example/models"
	"github.com/mgutz/razor/example/views"
)

// Index is generated
func Index(user *models.User) *razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	data := razor.M{
		"title": "Razor + Go = love",
	}

	body := func() *razor.SafeBuffer {
		_buffer := razor.NewSafeBuffer()
		views.Heading2("Admin area")

		_buffer.WriteString("Use foo sections for body to be consisten and it simplifies code")

		return _buffer
	}

	bodyFoot := func() *razor.SafeBuffer {
		_buffer := razor.NewSafeBuffer()

		_buffer.WriteString("<!-- <script> -->\n  <!--   alert('Hello, ")
		_buffer.WriteSafe(user.Name)
		_buffer.WriteString("'); -->\n  <!-- </script>")

		_buffer.WriteString("-->")
		return _buffer
	}

	_sections := make(razor.Sections)
	_sections["body"] = body()
	_sections["bodyFoot"] = bodyFoot()
	_buffer = Layout(data, _buffer, _sections)
	return _buffer
}
