// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package admin

import (
	"github.com/mgutz/razor"
)

func Render(path string, model interface{}) *razor.SafeBuffer {
	switch path {
	default:
		return razor.NewSafeBufferString("Invalid template: " + path)

	case "index":
		return Index(model)

	}
}
