// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package front

import (
	"github.com/mgutz/razor"
)

// Ignored_by_render is generated
func Ignored_by_render(__data interface{}, bar string) *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()
	__buffer.WriteString("\n\nIgnored by Render func since there are too many args.")

	return __buffer
}
