// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package front

import (
	"github.com/mgutz/razor"
	"github.com/mgutz/razor/example/models"
	"github.com/mgutz/razor/example/views"
	"github.com/mgutz/razor/html"
)

// Index is generated
func Index(user *models.User) *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()
	data := razor.M{
		"title": "Razor + Go = love",
	}
	__buffer.WriteString("\n\n<!-- helper.go -->")
	__buffer.WriteSafe(views.Heading2("FOO Razor rocks"))
	__buffer.WriteString("\n\n<p>Escaped: ")
	__buffer.WriteSafe(views.UnsafeHello(user.Name))
	__buffer.WriteString("</p>\n<p>Unescaped: ")
	__buffer.WriteSafe(views.SafeHello(user.Name))
	__buffer.WriteString("</p>\n\n<!-- avoid using Raw, create a function that returns SafeBuffer instead -->")
	__buffer.WriteSafe(html.Raw("<h2>Heading 2</h2>"))
	__buffer.WriteString("\n\n\n<h3>Code Block</h3>")

	isPositive := true
	if isPositive {

		__buffer.WriteString("Half full")

	} else {

		__buffer.WriteString("Half empty")

	}
	__buffer.WriteString("\n\n<h3>Combining Text and markup</h3>")
	fruits := []string{"apple", "orange", "pear"}
	__buffer.WriteString("\n\n<ul>\n    ")
	for _, fruit := range fruits {

		__buffer.WriteString("<li>")
		__buffer.WriteSafe(fruit)
		__buffer.WriteString("</li>")

	}
	__buffer.WriteString("\n</ul>\n\n<h3>Email address</h3>\n\nE-mail is special case that is recognized by Razor.")
	domain := "@mgutz.com"
	__buffer.WriteString("\n<p>mario@mgutz.com</p>\n<p>mario")
	__buffer.WriteSafe(domain)
	__buffer.WriteString("</p>\n\n<h3>Explicit expression</h3>")
	foo := "foo"

	foobar := "xxxxxx"
	if foobar == "" {
	}
	__buffer.WriteSafe((foo))
	__buffer.WriteString("bar\n\n\n<h3>Escaping the @sign</h3>\n\n@robinwilliams You so funny!\n\n<h3>Server Side Comment</h3>\n\n\nThis should be the only line\n\n<h3>Mixing expressions and text</h3>")

	title := "Mr"
	name := "Peabody"

	__buffer.WriteString("\nHello ")
	__buffer.WriteSafe(title)
	__buffer.WriteString(". ")
	__buffer.WriteSafe(name)
	__buffer.WriteString(".")

	__bodyFoot := func() *razor.SafeBuffer {
		__buffer := razor.NewSafeBuffer()

		__buffer.WriteString("<script>\n    console.log('Hello, ")
		__buffer.WriteSafe(user.Name)
		__buffer.WriteString("');\n  </script>")

		return __buffer
	}

	__sections := make(razor.Sections)
	__sections["bodyFoot"] = __bodyFoot()
	__buffer = Layout(data, __buffer, &__sections)
	return __buffer
}
