// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package front

import (
	"github.com/mgutz/razor"
	"github.com/mgutz/razor/example/models"
	"github.com/mgutz/razor/example/views"
	"github.com/mgutz/razor/html"
)

// Index is generated
func Index(user *models.User) *razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	locals := razor.Locals
	if locals != nil {
		// avoids not declared error if locals is not used
	}
	data := razor.ViewData{
		"title": "Razor + Go = love",
	}
	_buffer.WriteString("\n\n<!-- helper.go -->")
	_buffer.WriteSafe(views.Heading2("Razor rocks"))
	_buffer.WriteString("\n\n<p>Escaped: ")
	_buffer.WriteSafe(views.UnsafeHello(user.Name))
	_buffer.WriteString("</p>\n<p>Unescaped: ")
	_buffer.WriteSafe(views.SafeHello(user.Name))
	_buffer.WriteString("</p>\n\n<!-- avoid using Raw, create a function that returns SafeBuffer instead -->")
	_buffer.WriteSafe(html.Raw("<h2>Heading 2</h2>"))

	js := func() *razor.SafeBuffer {
		_buffer := razor.NewSafeBuffer()

		_buffer.WriteString("<script>\n    alert('Hello, ")
		_buffer.WriteSafe(user.Name)
		_buffer.WriteString("');\n  </script>")

		return _buffer
	}

	_sections := make(razor.Sections)
	_sections["js"] = js()
	_buffer = Layout(_buffer, _sections, data)
	return _buffer
}
