// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package front

import (
	"github.com/mgutz/razor"
)

// Layout is generated
func Layout(data razor.M, body *razor.SafeBuffer, sections razor.Sections) *razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()

	App := razor.App

	RenderBody := func() *razor.SafeBuffer {
		return body
	}

	RenderSection := func(section string, required ...bool) *razor.SafeBuffer {
		text := sections[section]
		isRequired := len(required) == 1 && required[0]
		if text == nil && isRequired {
			return razor.NewSafeBufferString("<div style='color:white; background-color: red'>SECTION " + section + " is required!<div>")
		}
		return text
	}
	_buffer.WriteString("\n\n<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\" />\n    <title>")
	_buffer.WriteSafe(data["title"])
	_buffer.WriteString("</title>\n    <link rel=\"stylesheet\" href=\"/")
	_buffer.WriteSafe(App["version"])
	_buffer.WriteString("/css/style.css\">\n<body>\n    <div class=\"container\">\n      ")
	_buffer.WriteSafe(RenderBody())
	_buffer.WriteString("\n    </div>\n    ")
	_buffer.WriteSafe(data["footer"])
	_buffer.WriteString("\n    ")
	_buffer.WriteSafe(RenderSection("bodyFoot"))
	_buffer.WriteString("\n  </body>\n</html>")

	return _buffer
}
