// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package front

import (
	"github.com/mgutz/razor"
)

// Render returns the generated template function for a given path.
// Layouts are not included.
func Render(path string, model interface{}) *razor.SafeBuffer {
	switch path {
	default:
		return razor.NewSafeBufferString("Invalid template: " + path)

	case "index":
		return Index(model)

	}
}
